### ISSUE TITLE
Update teamspeak version in defaults

### ISSUE THREAD

**Issue by EggieCode** [stejoo/ansible-teamspeak#11]
New teamspeak version is available.
http://forum.teamspeak.com/threads/126318-TeamSpeak-3-Server-3-0-13-2-released

**Comment by stejoo** [comment]
Thanks for letting me know. I'll try to test it tomorrow.

**Comment by stejoo** [comment]
I noticed 3.0.13.3 is now also available. Yet there doesn't seem to be a release announcement for it.

**Comment by stejoo** [comment]
Merged with commit 393ef2484f004c136543b55cdd00a253961f2d44
