### ISSUE TITLE
Allow updating of the TeamSpeak 3 server

### ISSUE THREAD

**Issue by stejoo** [stejoo/ansible-teamspeak#2]
Make it possible to have the Ansible role perform upgrades of the TeamSpeak 3 server by incrementing the version number and associated checksum.

New teamspeak server would be installed in a new directory. Follow up:
- Have Ansible copy the database and other extra files over to the new TeamSpeak 3 server's directory.
- Cleanup of former versions. Keeping only 1 previous version for example in case we want/need to fall back.

**Comment by stejoo** [comment]
Idea I had yesterday:
Copy current Teamspeak 3 server directory and extract the new one over it. Just as suggested by the TeamSpeak 3 server upgrade instructions. 

By using a symlink to refer to a currently active TeamSpeak 3 server installation I will always have a valid source location to look for current configuration and data files.

Pseudo-tasks:

<pre>
0. Was a TeamSpeak 3 server directory (for a new version) made?
  Yes?
  1. Check for existence of a current version with user data (in symlink dir)
    Exists? 
    include: ts3update.yml ::
      2.  Stop currently running TS3Server
      3a. Copy current version to new directory
       b. Queue handler to perform cleanup of old TS3Server version(s)
  4. Extract new version to new directory, overwriting
5. Set a symlink to current TeamSpeak 3 server path
Continue...
</pre>

Another idea is to make the amount of older versions to keep around configurable through a variable.

**Comment by stejoo** [comment]
Updating version alpha available in the "issue2" branch. See https://github.com/stejoo/ansible-teamspeak/tree/issue2

**Comment by EggieCode** [comment]
Idea: Check of users on the server? With the serverquery.
And option to set to not to delete old folder.

**Comment by stejoo** [comment]
> Idea: Check of users on the server? With the serverquery.

You mean to see if people are online at the moment? And have the playbook fail when somebody is logged on? 

> And option to set to not to delete old folder.

Did you see my idea of making the amount of old versions to keep configurable?  
The default would be not to delete the old TS3server directory. So if an upgrade goes wrong, you can enter the old version and checksum, run the role, it should only fix the symlink and it restart the server after doing so (will fix that last one right now).

If, for whatever reason, you want the role never to delete anything I would suggest setting a very high number at this future variable.

**Comment by EggieCode** [comment]
> You mean: See if people are online at this moment? And have the playbook fail when somebody is logged on? 

Not that hard to open een telnet connection to read that out. Only you need a serveradmin password.

> If, for whatever reason, you want the role never to delete anything I would suggest setting a very high number at this future variable.

It that a big problem with a folder of not more 100MB?

And u need to remember to copy/symlink the SQlite database.

**Comment by stejoo** [comment]
> Not that hard to open een telnet connection to read that out. Only you need a serveradmin password.

Good to know. But you didn't answer the question. Did I understand your intentions of aborting an upgrade when people are logged on correctly? If so, I would like to ask you to open a new issue for it. I feel it is outside of the scope of this issue. Please provide information about what is desired and how you think this could be accomplished in such a new issue.

> It that a big problem with a folder of not more 100MB?

Not at all. It depends on the space you have available. I see no reason to keep more than 1 or 2 older versions around myself. If you want to keep more, you could set the number to keep to 10, 100, 1000, ... 

> And u need to remember to copy/symlink the SQlite database.

As far as I'm aware: this is taken care of. The entire directory (and contents) is copied and the updated archive is extracted over it; As recommended by the updating instructions included with TeamSpeak 3 Server. Please have a look at the task files.

**Comment by EggieCode** [comment]
> As far as I'm aware: this is taken care of. The entire directory (and contents) is copied and the updated archive is extracted over it; As recommended by the updating instructions included with TeamSpeak 3 Server. Please have a look at the task files.

For the record you not copying the SQLite file.
`Checking for a currently installed TeamSpeak 3 server with user data`
Only copys files directory. That stores the filetranfer data and user avatars.

Maybe a good idea to symlink the datafolder and the SQLlite file to _{{teamspeak.home}}_.
So you don't need to care about it.

The database file is called _ts3server.sqlitedb_.

**Comment by stejoo** [comment]
That "Checking" tasks decides only if we're going to include the update tasks or not. It does not copy anything itself. The task looks if a current TeamSpeak 3 server directory might contain user data (files, logs, sqlite) and register a variable when it's found something. Which is in turn used to include ts3update.yml.

Please have a look at the [ts3update.yml](https://github.com/stejoo/ansible-teamspeak/blob/issue2/tasks/ts3update.yml) task file. It executes a <tt>synchronize</tt> to copy the _entire_ directory, including the database, before extracting a new version over it.
