### ISSUE TITLE
Remove old versions misbehaves

### ISSUE THREAD

**Issue by conrad784** [stejoo/ansible-teamspeak#20]
The latest release of TS3 is 3.10.2.
Sorting like here https://github.com/stejoo/ansible-teamspeak/blob/b44d11f0d98e6694e75fc4c8565ef5f7612b414c/handlers/main.yml#L16
will remove false versions as normal sort will result in 1,10,2,3,4,5,...
I solved this in my fork with `sort -V`
https://github.com/conrad784/ansible-teamspeak/commit/e3fd2b507d349ad3935bb62f1c7ae3492d213a95

I am not sure this will work on BSD though.

**Comment by stejoo** [comment]
Good catch, I'll look into it.

**Comment by stejoo** [comment]
BSD seems to have it in all supported releases.
I'll call `sort` with this option as well from now on. Thanks, i'll update in a minute.
