### ISSUE TITLE
Add support for including a TeamSpeak 3 license file

### ISSUE THREAD

**Issue by stejoo** [stejoo/ansible-teamspeak#3]
Add support for the role to install a supplied TeamSpeak 3 license to a new installation (and upgrades hopefully).

**Comment by stejoo** [comment]
I had a go and this seems to work on my end. Went well as far as I can tell.

@EggieCode Thanks for lending me your expired license file to test with. 
@EggieCode would you like to test this with a active license on your end?

**Comment by EggieCode** [comment]
I can do that.
Maybe add a local source path of the license key?

**Comment by stejoo** [comment]
Could make it a variable yes. On it.

**Comment by stejoo** [comment]
Made the source file configurable in commit 7ef374edd6f40c1d8a754fdd58dba22efb707932 .
